### ISSUE TITLE
Requirement of zeromq with draft API

### ISSUE THREAD

**Issue by UndeadKernel** [dzop/emacs-zmq#1]
Hey @dzop,

The library works very well. However, I faced many issues installing libzmq with draft API support. Most distributions do not supply the library with that compilation option enabled. In Arch GNU/Linux, for example, the package zeromq (which supplies libzmq) has to be recompiled from scratch and manually set to enable the draft APIs.

I was thinking that two paths could be taken to make this library easier to install for others:
1) Only use the non-draft API and detect if it's enabled for optional functionality.
2) Provide a static local library (of libzmq) and compile it at installation time.

Do you think any of those two are a possibility?

**Comment by nnicandro** [comment]
I think (2) looks pretty good. It would simplify building and testing with Travis since I have to build `zmq` from scratch there as well. Actually, any project that depends on `emacs-zmq` and would like to test their project using Travis would have to build `zmq`. This is what I had to do in `emacs-jupyter`.

It would also be a step forward in supporting Windows in the future since then `emacs-zmq` would be responsible for all the complications that come with building packages on Windows.
