### ISSUE TITLE
Signature doesnt match

### ISSUE THREAD

**Issue by zeneofa** [dzop/emacs-zmq#15]
Hi,

I am encountering signature verification issues, the error is:

```
Check for compatible module binary to download? (y or n) y
Downloading https://github.com/dzop/emacs-zmq/releases/download/v0.10.10/emacs-zmq-x86_64-w64-mingw32.tar.gz
Verifying sha256 signature of emacs-zmq-x86_64-w64-mingw32.tar.gz
zmq--download-and-extract-file: Signature did not match content

```

My system is:
Windows 10
Using emacs obtained from: `https://github.com/m-parashar/emax64`
Emacs version 26.2
Spacemacs version 0.300 (develop)
jupyter and python installed using anaconda

The error occurs when running the `jupyter-run-repl` function from the emacs-jupyter repo. The issue posted on that rep is linked here: [emacs-jupyter issue 168](https://github.com/dzop/emacs-jupyter/issues/168#issuecomment-530519262)

this also happens if I just run `(require 'zmq)` in the scratch buffer

**Comment by fleimgruber** [comment]
I am able to reproduce this with Emacs 27 as well. I tried to edebug this and the `(buffer-string)` in https://github.com/dzop/emacs-zmq/blob/master/zmq.el#L599 should work on the temporary buffer, but in edebug session refers to openend `zmq.el` buffer. Any ideas on how to debug this further?

@dzop Maybe we could download into a dedicated buffer that is able to be inspected for debugging?

**Comment by nnicandro** [comment]
Sorry for the delay.

The code below shows how you can get the `.tar.gz` file to inspect. The `tgz` variable is the `.tar.gz` file contents which you can write to file or display in some buffer.

Can you show the signatures that the code prints. If they are different, maybe try to substitute the `secure-hash` call with
`(secure-hash 'sha256 (encode-coding-string tgz 'utf-8-unix))`. I suspect the issue lies in the default coding system used on Windows since the signatures match on my Linux machine.

I would actually like to get away from comparing the hash of the downloaded `.tar.gz` file with a signature from *another* downloaded file and would prefer to hard-code those signatures somewhere in `zmq.el` instead.

```elisp
(let* ((tgz-url "https://github.com/dzop/emacs-zmq/releases/download/v0.10.10/emacs-zmq-x86_64-w64-mingw32.tar.gz")
       (tgz (with-temp-buffer
              (zmq--insert-url-contents tgz-url)
              (goto-char (point-min))
              (buffer-string)))
       (tgz-sig (with-temp-buffer
                  (zmq--insert-url-contents (concat tgz-url ".sha256"))
                  (pop-to-buffer (current-buffer))
                  (goto-char (point-min))
                  (forward-sexp)
                  (let ((end (point)))
                    (backward-sexp)
                    (buffer-substring (point) end)))))
  (list tgz-sig (secure-hash 'sha256 tgz)))
```
